"""
Used to identify the relationship between the csv data and the data that is being massaged and being sent to
"""
from models.TableFieldDataClass import TableField
from models.tables import (
    agencies,
    nibrs_activity_type,
    nibrs_age,
    nibrs_arrest_type,
    nibrs_arrestee,
    nibrs_arrestee_weapon,
    nibrs_assignment_type,
    nibrs_bias_list,
    nibrs_bias_motivation,
    nibrs_circumstances,
    nibrs_cleared_except,
    nibrs_criminal_act_type,
    nibrs_criminal_act,
    nibrs_drug_measure_type,
    nibrs_ethnicity,
    nibrs_incident,
    nibrs_injury,
    nibrs_justifiable_force,
    nibrs_location_type,
    nibrs_month,
    nibrs_offender,
    nibrs_offense,
    nibrs_offense_type,
    nibrs_prop_desc_type,
    nibrs_prop_loss_type,
    nibrs_property,
    nibrs_property_desc,
    nibrs_relationship,
    nibrs_suspect_using,
    nibrs_suspected_drug,
    nibrs_suspected_drug_type,
    nibrs_using_list,
    nibrs_victim,
    nibrs_victim_circumstances,
    nibrs_victim_injury,
    nibrs_victim_offender_rel,
    nibrs_victim_offense,
    nibrs_victim_type,
    nibrs_weapon,
    nibrs_weapon_type,
    ref_race,
    ref_state,
)


def get_relationship() -> dict[str, list[TableField]]:
    return {
        "agencies.csv": agencies.get_headers(),
        "NIBRS_ACTIVITY_TYPE.csv": nibrs_activity_type.get_headers(),
        "NIBRS_AGE.csv": nibrs_age.get_headers(),
        "NIBRS_ARREST_TYPE.csv": nibrs_arrest_type.get_headers(),
        "NIBRS_ARRESTEE.csv": nibrs_arrestee.get_headers(),
        "NIBRS_ARRESTEE_WEAPON.csv": nibrs_arrestee_weapon.get_headers(),
        "NIBRS_ASSIGNMENT_TYPE.csv": nibrs_assignment_type.get_headers(),
        "NIBRS_BIAS_LIST.csv": nibrs_bias_list.get_headers(),
        "NIBRS_BIAS_MOTIVATION.csv": nibrs_bias_motivation.get_headers(),
        "NIBRS_CIRCUMSTANCES.csv": nibrs_circumstances.get_headers(),
        "NIBRS_CLEARED_EXCEPT.csv": nibrs_cleared_except.get_headers(),
        "NIBRS_CRIMINAL_ACT.csv": nibrs_criminal_act.get_headers(),
        "NIBRS_CRIMINAL_ACT_TYPE.csv": nibrs_criminal_act_type.get_headers(),
        "NIBRS_DRUG_MEASURE_TYPE.csv": nibrs_drug_measure_type.get_headers(),
        "NIBRS_ETHNICITY.csv": nibrs_ethnicity.get_headers(),
        "NIBRS_incident.csv": nibrs_incident.get_headers(),
        "NIBRS_INJURY.csv": nibrs_injury.get_headers(),
        "NIBRS_JUSTIFIABLE_FORCE.csv": nibrs_justifiable_force.get_headers(),
        "NIBRS_LOCATION_TYPE.csv": nibrs_location_type.get_headers(),
        "NIBRS_month.csv": nibrs_month.get_headers(),
        "NIBRS_OFFENDER.csv": nibrs_offender.get_headers(),
        "NIBRS_OFFENSE.csv": nibrs_offense.get_headers(),
        "NIBRS_OFFENSE_TYPE.csv": nibrs_offense_type.get_headers(),
        "NIBRS_PROP_DESC_TYPE.csv": nibrs_prop_desc_type.get_headers(),
        "NIBRS_PROP_LOSS_TYPE.csv": nibrs_prop_loss_type.get_headers(),
        "NIBRS_PROPERTY.csv": nibrs_property.get_headers(),
        "NIBRS_PROPERTY_DESC.csv": nibrs_property_desc.get_headers(),
        "NIBRS_RELATIONSHIP.csv": nibrs_relationship.get_headers(),
        "NIBRS_SUSPECT_USING.csv": nibrs_suspect_using.get_headers(),
        "NIBRS_SUSPECTED_DRUG.csv": nibrs_suspected_drug.get_headers(),
        "NIBRS_SUSPECTED_DRUG_TYPE.csv": nibrs_suspected_drug_type.get_headers(),
        "NIBRS_USING_LIST.csv": nibrs_using_list.get_headers(),
        "NIBRS_VICTIM.csv": nibrs_victim.get_headers(),
        "NIBRS_VICTIM_CIRCUMSTANCES.csv": nibrs_victim_circumstances.get_headers(),
        "NIBRS_VICTIM_INJURY.csv": nibrs_victim_injury.get_headers(),
        "NIBRS_VICTIM_OFFENDER_REL.csv": nibrs_victim_offender_rel.get_headers(),
        "NIBRS_VICTIM_OFFENSE.csv": nibrs_victim_offense.get_headers(),
        "NIBRS_VICTIM_TYPE.csv": nibrs_victim_type.get_headers(),
        "NIBRS_WEAPON.csv": nibrs_weapon.get_headers(),
        "NIBRS_WEAPON_TYPE.csv": nibrs_weapon_type.get_headers(),
        "REF_RACE.csv": ref_race.get_headers(),
        "REF_STATE.csv": ref_state.get_headers(),
    }
