repos:
- repo: https://github.com/psf/black
  rev: 20.8b1
  hooks:
    - id: black
      language_version: python3
      stages: [commit]
- repo: local
  hooks:
    - id: commit-message-check
      name: check commit message format
      entry: python3 spark_bulk_data/commit_message.py
      language: python
      always_run: true
      stages: [commit-msg]