from spark_bulk_data.models.TableFieldDataClass import TableField
from spark_bulk_data.config import SQLConfig


def get_headers() -> list[TableField]:
    return [
        TableField(
            name="YEARLY_AGENCY_ID", sql_type=SQLConfig.Types.INTEGER, is_primary=True
        ),
        TableField(name="AGENCY_ID", sql_type=SQLConfig.Types.INTEGER),
        TableField(name="DATA_YEAR", sql_type=SQLConfig.Types.INTEGER),
        TableField(name="ORI", sql_type=SQLConfig.Types.STRING),
        TableField(name="LEGACY_ORI", sql_type=SQLConfig.Types.STRING),
        TableField(name="COVERED_BY_LEGACY_ORI", sql_type=SQLConfig.Types.STRING),
        TableField(name="DIRECT_CONTRIBUTOR_FLAG", sql_type=SQLConfig.Types.STRING),
        TableField(name="DORMANT_FLAG", sql_type=SQLConfig.Types.STRING),
        TableField(name="REPORTING_TYPE", sql_type=SQLConfig.Types.STRING),
        TableField(name="UCR_AGENCY_NAME", sql_type=SQLConfig.Types.STRING),
        TableField(name="NCIC_AGENCY_NAME", sql_type=SQLConfig.Types.STRING),
        TableField(name="PUB_AGENCY_NAME", sql_type=SQLConfig.Types.STRING),
        TableField(name="PUB_AGENCY_UNIT", sql_type=SQLConfig.Types.STRING),
        TableField(name="AGENCY_STATUS", sql_type=SQLConfig.Types.STRING),
        TableField(name="STATE_ID", sql_type=SQLConfig.Types.INTEGER),
        TableField(name="STATE_NAME", sql_type=SQLConfig.Types.STRING),
        TableField(name="STATE_ABBR", sql_type=SQLConfig.Types.STRING),
        TableField(name="STATE_POSTAL_ABBR", sql_type=SQLConfig.Types.STRING),
        TableField(name="DIVISION_CODE", sql_type=SQLConfig.Types.INTEGER),
        TableField(name="DIVISION_NAME", sql_type=SQLConfig.Types.STRING),
        TableField(name="REGION_CODE", sql_type=SQLConfig.Types.INTEGER),
        TableField(name="REGION_NAME", sql_type=SQLConfig.Types.STRING),
        TableField(name="REGION_DESC", sql_type=SQLConfig.Types.STRING),
        TableField(name="AGENCY_TYPE_NAME", sql_type=SQLConfig.Types.STRING),
        TableField(name="POPULATION", sql_type=SQLConfig.Types.INTEGER),
        TableField(name="SUBMITTING_AGENCY_ID", sql_type=SQLConfig.Types.INTEGER),
        TableField(name="SAI", sql_type=SQLConfig.Types.STRING),
        TableField(name="SUBMITTING_AGENCY_NAME", sql_type=SQLConfig.Types.STRING),
        TableField(name="SUBURBAN_AREA_FLAG", sql_type=SQLConfig.Types.STRING),
        TableField(name="POPULATION_GROUP_ID", sql_type=SQLConfig.Types.INTEGER),
        TableField(name="POPULATION_GROUP_CODE", sql_type=SQLConfig.Types.INTEGER),
        TableField(name="POPULATION_GROUP_DESC", sql_type=SQLConfig.Types.STRING),
        TableField(name="PARENT_POP_GROUP_CODE", sql_type=SQLConfig.Types.STRING),
        TableField(name="PARENT_POP_GROUP_DESC", sql_type=SQLConfig.Types.STRING),
        TableField(name="MIP_FLAG", sql_type=SQLConfig.Types.STRING),
        TableField(name="POP_SORT_ORDER", sql_type=SQLConfig.Types.INTEGER),
        TableField(name="SUMMARY_RAPE_DEF", sql_type=SQLConfig.Types.STRING),
        TableField(name="PE_REPORTED_FLAG", sql_type=SQLConfig.Types.STRING),
        TableField(name="MALE_OFFICER", sql_type=SQLConfig.Types.INTEGER),
        TableField(name="MALE_CIVILIAN", sql_type=SQLConfig.Types.INTEGER),
        TableField(
            name="PED.MALE_OFFICER+PED.MALE_CIVILIAN", sql_type=SQLConfig.Types.INTEGER
        ),
        TableField(name="FEMALE_OFFICER", sql_type=SQLConfig.Types.STRING),
        TableField(name="FEMALE_CIVILIAN", sql_type=SQLConfig.Types.STRING),
        TableField(
            name="PED.FEMALE_CIVILIAN+PED.FEMALE_OFFICER",
            sql_type=SQLConfig.Types.STRING,
        ),
        TableField(name="NIBRS_CERT_DATE", sql_type=SQLConfig.Types.DATE),
        TableField(name="NIBRS_START_DATE", sql_type=SQLConfig.Types.DATE),
        TableField(name="NIBRS_LEOKA_START_DATE", sql_type=SQLConfig.Types.DATE),
        TableField(name="NIBRS_CT_START_DATE", sql_type=SQLConfig.Types.DATE),
        TableField(name="NIBRS_MULTI_BIAS_START_DATE", sql_type=SQLConfig.Types.DATE),
        TableField(name="NIBRS_OFF_ETH_START_DATE", sql_type=SQLConfig.Types.DATE),
        TableField(name="COVERED_FLAG", sql_type=SQLConfig.Types.STRING),
        TableField(name="COUNTY_NAME", sql_type=SQLConfig.Types.STRING),
        TableField(name="MSA_NAME", sql_type=SQLConfig.Types.STRING),
        TableField(name="PUBLISHABLE_FLAG", sql_type=SQLConfig.Types.STRING),
        TableField(name="PARTICIPATED", sql_type=SQLConfig.Types.STRING),
        TableField(name="NIBRS_PARTICIPATED", sql_type=SQLConfig.Types.STRING),
    ]
